### ISSUE TITLE
Hooks returns 401 Unhautorized

### ISSUE THREAD

**Issue by bagerard** [kadrach/pre-commit-gitlabci-lint#3]
It looks like Gitlab's API receive some updates, running the hook currently fails with:

```
Using linter: https://gitlab.com/api/v4/ci/lint
Error connecting to Gitlab: HTTP Error 401: Unauthorized
```

I'm only observing that against gitlab.com, if I target our own instance of gitlab which runs an older version, it runs fine. It sounds like it will require authentication...

Thanks for the hooks BTW!

**Comment by kadrach** [comment]
Thanks for reporting this. 

It looks like there have been some changes on the GitLab side, though I was unable to find the issue/MR on the GitLab side right away. GitLab also appear to have added a number of features to their `.gitlab-ci.yml` spec and the `/lint` endpoints that I was not aware of, as I don't use GitLab anymore.

Will try to have a look at this soon. As always, PRs welcome :)

**Comment by bagerard** [comment]
I had a quick look with curl, starting from the CI linter from gitlab and only thing I can tell is that I get the 401 as soon as I start removing headers like `x-csrf-token` or `_gitlab_session`

`curl 'https://gitlab.com/api/v4/ci/lint'   -H 'authority: gitlab.com'   -H 'accept: application/json, text/plain, */*'   -H 'x-csrf-token: h/pJa2jK(...rest of token...)'   -H 'x-requested-with: XMLHttpRequest'   -H 'content-type: application/json;charset=UTF-8'   -H 'origin: https://gitlab.com'   -H 'cookie: _gitlab_session=ec86(...rest of token...); event_filter=all'   --data-raw '{"content":"a_wrong_ci_file","dry_run":false}'   --compressed`

If gitlab persists in requiring authentication for this endpoint, it will be problematic for this hook. I don't think there is anything we can do about it from this repo

**Comment by kadrach** [comment]
Authorising via a PAT may work, in which case the hook could require an environment variable containing a PAT to be set.

**Comment by bagerard** [comment]
Indeed this should work and is probably straightforward to set up in a CI but it's a different story for local use of the pre-commit hook (as it means extra set up for developers) and this hook is mostly valuable locally unfortunately

**Comment by rooterkyberian** [comment]
Issue about upstream change - https://gitlab.com/gitlab-org/gitlab/-/issues/321290 . Since it was done to tighten security I doubt they will revert this change ever.

Sadly there is no hope for reusing SSH keys devs typically do have on their machines to access Gitlab API https://gitlab.com/gitlab-org/gitlab/-/issues/215242 .

This needs to be double checked since I'm not 100% sure you can share globally configured app across all gitlab users securly, but OAuth2 - [Authorization code with Proof Key for Code Exchange (PKCE)]( https://docs.gitlab.com/ee/api/oauth2.html#authorization-code-with-proof-key-for-code-exchange-pkce) flow seems to be a way to do it. It will prompt user through browser to authorize the request, so can't use it as non-interactive CLI-only tool, but if we are thinking about making sure changes done by developers are ready to be commited - then we expect a live human to be in front of screen anyway.

For CI tool we would still need to support much easier to implement tokens passed through ENVs, but in other cases I think we should fallback to oauth2. IMO An option to prevent oauth2 fallback should be added as well to prevent of CI idlying in case of bad configuration.

**Comment by bagerard** [comment]
Surprisingly gitlab reverted this after people complained :D (https://gitlab.com/gitlab-org/gitlab/-/issues/321290)
This got released on the public gitlab version. I guess we can close this
:tada:
